name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_DEPLOY_KEY}}
    - name: Restore
      run: dotnet restore FingerPuppet/FingerPuppet.csproj
    - name: Build
      run: dotnet build FingerPuppet/FingerPuppet.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - run: mkdir ${{ github.workspace }}/Artifacts
    - name: Pack
      run: dotnet pack FingerPuppet/FingerPuppet.csproj --include-symbols --configuration Release -o ${{ github.workspace }}/Artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: Upload artifacts
        path:  ${{ github.workspace }}/Artifacts
